In [1]:

import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset shape: (891, 15)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [2]:

df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [3]:

cleaned_df = df.copy()

print("Original dataset shape:", df.shape)
print("Working copy shape:", cleaned_df.shape)

Original dataset shape: (891, 15)
Working copy shape: (891, 15)

In [4]:

cleaned_df["age"] = cleaned_df["age"].fillna(
    cleaned_df["age"].median()
)

print("Missing age values after cleaning:")
print(cleaned_df["age"].isnull().sum())

Missing age values after cleaning:
0

In [5]:

print("Missing embarked values before cleaning:")
print(cleaned_df["embarked"].isnull().sum())

print("Most frequent embarked value:")
print(cleaned_df["embarked"].mode()[0])

Missing embarked values before cleaning:
2
Most frequent embarked value:
S

In [6]:

cleaned_df["embarked"] = cleaned_df["embarked"].fillna(
    cleaned_df["embarked"].mode()[0]
)

print("Missing embarked values after cleaning:")
print(cleaned_df["embarked"].isnull().sum())

Missing embarked values after cleaning:
0

In [7]:

print("Missing embark_town values before cleaning:")
print(cleaned_df["embark_town"].isnull().sum())

print("\nMost frequent embark_town value:")
print(cleaned_df["embark_town"].mode()[0])

Missing embark_town values before cleaning:
2

Most frequent embark_town value:
Southampton

In [8]:

cleaned_df["embark_town"] = cleaned_df["embark_town"].fillna(
    cleaned_df["embark_town"].mode()[0]
)

print("Missing embark_town values after cleaning:")
print(cleaned_df["embark_town"].isnull().sum())

Missing embark_town values after cleaning:
0

In [9]:

print("Missing deck values before cleaning:")
print(cleaned_df["deck"].isnull().sum())

Missing deck values before cleaning:
688

In [10]:

cleaned_df["deck"] = cleaned_df["deck"].fillna("Unknown")

print("Missing deck values after cleaning:")
print(cleaned_df["deck"].isnull().sum())

print("\nUnknown deck values:")
print((cleaned_df["deck"] == "Unknown").sum())

Missing deck values after cleaning:
0

Unknown deck values:
688

In [11]:

print("Missing values in each column:")
print(cleaned_df.isnull().sum())

print("\nTotal missing values remaining:")
print(cleaned_df.isnull().sum().sum())

Missing values in each column:
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

Total missing values remaining:
0

In [12]:

print("Duplicate records before removal:")
print(cleaned_df.duplicated().sum())

Duplicate records before removal:
110

In [13]:

cleaned_df = cleaned_df.drop_duplicates()

print("Duplicate records after removal:")
print(cleaned_df.duplicated().sum())

print("\nDataset shape after removing duplicates:")
print(cleaned_df.shape)

Duplicate records after removal:
0

Dataset shape after removing duplicates:
(781, 15)

In [14]:

print("Remaining duplicate records:",
      cleaned_df.duplicated().sum())

print("Rows after cleaning:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

Remaining duplicate records: 0
Rows after cleaning: 781
Columns: 15

In [15]:

print("Data types before correction:")
print(cleaned_df.dtypes)

Data types before correction:
survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

In [16]:

for col in ["survived", "pclass", "sibsp", "parch"]:
    cleaned_df[col] = cleaned_df[col].astype("int64")

for col in ["age", "fare"]:
    cleaned_df[col] = pd.to_numeric(cleaned_df[col], errors="coerce")

text_cols = [
    "sex", "embarked", "class", "who",
    "deck", "embark_town", "alive"
]

for col in text_cols:
    cleaned_df[col] = cleaned_df[col].astype("string")

for col in ["adult_male", "alone"]:
    cleaned_df[col] = cleaned_df[col].astype("bool")

print("Data types after correction:")
print(cleaned_df.dtypes)

Data types after correction:
survived                int64
pclass                  int64
sex            string[python]
age                   float64
sibsp                   int64
parch                   int64
fare                  float64
embarked       string[python]
class          string[python]
who            string[python]
adult_male               bool
deck           string[python]
embark_town    string[python]
alive          string[python]
alone                    bool
dtype: object

In [17]:

print("Data type validation:")

print("Integer columns:",
      all(cleaned_df[c].dtype == "int64"
          for c in ["survived", "pclass", "sibsp", "parch"]))

print("Numeric columns:",
      all(pd.api.types.is_numeric_dtype(cleaned_df[c])
          for c in ["age", "fare"]))

print("Text columns:",
      all(cleaned_df[c].dtype == "string"
          for c in text_cols))

print("Boolean columns:",
      all(cleaned_df[c].dtype == "bool"
          for c in ["adult_male", "alone"]))

Data type validation:
Integer columns: True
Numeric columns: True
Text columns: True
Boolean columns: True

In [18]:

text_cols = [
    "sex", "embarked", "class", "who",
    "deck", "embark_town", "alive"
]

print("Checking text columns for extra spaces:\n")

for col in text_cols:
    spaces = cleaned_df[col].str.strip().ne(cleaned_df[col]).sum()
    print(col, ":", spaces, "values with extra spaces")

print("\nUnique values in each text column:\n")

for col in text_cols:
    print(col, ":", cleaned_df[col].unique())

Checking text columns for extra spaces:

sex : 0 values with extra spaces
embarked : 0 values with extra spaces
class : 0 values with extra spaces
who : 0 values with extra spaces
deck : 0 values with extra spaces
embark_town : 0 values with extra spaces
alive : 0 values with extra spaces

Unique values in each text column:

sex : <StringArray>
['male', 'female']
Length: 2, dtype: string
embarked : <StringArray>
['S', 'C', 'Q']
Length: 3, dtype: string
class : <StringArray>
['Third', 'First', 'Second']
Length: 3, dtype: string
who : <StringArray>
['man', 'woman', 'child']
Length: 3, dtype: string
deck : <StringArray>
['Unknown', 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Length: 8, dtype: string
embark_town : <StringArray>
['Southampton', 'Cherbourg', 'Queenstown']
Length: 3, dtype: string
alive : <StringArray>
['no', 'yes']
Length: 2, dtype: string

In [19]:

for col in text_cols:
    cleaned_df[col] = cleaned_df[col].str.strip()

print("Text values standardized successfully!")

for col in text_cols:
    print(col, ":", cleaned_df[col].nunique(), "unique values")

Text values standardized successfully!
sex : 2 unique values
embarked : 3 unique values
class : 3 unique values
who : 3 unique values
deck : 8 unique values
embark_town : 3 unique values
alive : 2 unique values

In [20]:

print("FINAL DATA CLEANING REPORT")
print("--------------------------")

print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])
print("Total missing values:", cleaned_df.isnull().sum().sum())
print("Duplicate records:", cleaned_df.duplicated().sum())

print("\nMissing values by column:")
print(cleaned_df.isnull().sum())

print("\nFinal validation completed!")

FINAL DATA CLEANING REPORT
--------------------------
Rows: 781
Columns: 15
Total missing values: 0
Duplicate records: 0

Missing values by column:
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

Final validation completed!

In [21]:

cleaned_df.to_csv("titanic_cleaned.csv", index=False)

from google.colab import files
files.download("titanic_cleaned.csv")